export const DATA_1 = [
  "/images/latest-work/arthanadi.png",
  "/images/latest-work/brankcut.png",
  "/images/latest-work/bilikcoding-1.png",
  "/images/latest-work/bomnuts-1.png",
  "/images/latest-work/tawa-1.png",
  "/images/latest-work/bomnuts-2.png",
  "/images/latest-work/minbeauty.png",
  "/images/latest-work/sunfor-1.png",
  "/images/latest-work/tawa-2.png",
  "/images/latest-work/mugoporto-1.png",
  "/images/latest-work/sunfor-3.png",
  "/images/latest-work/tawa-3.png",
  "/images/latest-work/bilikcoding-2.png",
  "/images/latest-work/sunfor-2.png",
  "/images/latest-work/bilikcoding-4.png",
]

export const DATA_2 = [
  "/images/latest-work/brankcut.png",
  "/images/latest-work/bomnuts-1.png",
  "/images/latest-work/tawa-1.png",
  "/images/latest-work/bilikcoding-1.png",
  "/images/latest-work/mugoporto-1.png",
  "/images/latest-work/bomnuts-2.png",
  "/images/latest-work/arthanadi.png",
  "/images/latest-work/sunfor-3.png",
  "/images/latest-work/bilikcoding-4.png",
  "/images/latest-work/tawa-2.png",
  "/images/latest-work/sunfor-2.png",
  "/images/latest-work/tawa-3.png",
  "/images/latest-work/minbeauty.png",
  "/images/latest-work/bilikcoding-2.png",
  "/images/latest-work/sunfor-1.png",
]

export const DATA_3 = [
  "/images/latest-work/tawa-1.png",
  "/images/latest-work/sunfor-2.png",
  "/images/latest-work/bilikcoding-1.png",
  "/images/latest-work/mugoporto-1.png",
  "/images/latest-work/bomnuts-1.png",
  "/images/latest-work/bilikcoding-4.png",
  "/images/latest-work/bomnuts-2.png",
  "/images/latest-work/brankcut.png",
  "/images/latest-work/sunfor-3.png",
  "/images/latest-work/sunfor-1.png",
  "/images/latest-work/bilikcoding-2.png",
  "/images/latest-work/tawa-2.png",
  "/images/latest-work/arthanadi.png",
  "/images/latest-work/tawa-3.png",
  "/images/latest-work/minbeauty.png",
]
