/* eslint-disable react/no-unescaped-entities */
import Container from "@/components/elements/Container"
import ContactUs from "@/composites/ContactUs/ContactUs"
import FAQ from "@/composites/FAQ/FAQ"
import OurLatestWork from "@/composites/OurLatestWork/OurLatestWork"
import OurService from "@/composites/OurService/OurService"
import WhyUs from "@/composites/WhyUs/WhyUs"
import WorkingProcess from "@/composites/WorkingProcess/WorkingProcess"
import useScroll from "@/hooks/useScroll"
import { motion } from "framer-motion"
import Head from "next/head"
import Link from "next/link"
import { useEffect, useState } from "react"
import { MapPinIcon, EnvelopeIcon, Bars2Icon } from "@heroicons/react/24/solid"
import Footer from "@/composites/Footer/Footer"
import Header from "@/composites/Header/Header"

export default function Home() {
  const scrollPosition = useScroll()
  const [degree, setDegree] = useState(0)

  useEffect(() => {
    setDegree(window.pageYOffset / 4)
  }, [scrollPosition])

  return (
    <>
      <Head>
        <title>Arip Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Hero Section */}
      <Container className="mt-[80px]">
        <section className="py-0 sm:pt-[60px] sm:pb-[100px]">
          <div className="h-[650px] flex items-center">
            <div className="relative">
              <h1 className="text-[52px] md:text-[136px] font-medium leading-none text-white w-[90%] relative z-10">
                Empowering <span className="text-primary">Your Personal Brand</span> to Reach New
                Heights.
              </h1>
              <img
                src="/images/highlighter.svg"
                className="hidden sm:block absolute bottom-[50px] right-[220px] w-[750px]"
              />
              <div className="relative pt-10">
                <hr className="mb-10" />
                <div className="hidden w-[80px] h-[80px] md:w-[160px] md:h-[160px] bg-primary rounded-full absolute right-14 top-[-40px] sm:flex items-center justify-center">
                  <img
                    src="/images/best-visual-service.svg"
                    className="ease-linear duration-100"
                    alt=""
                    style={{ transform: `rotate(${degree}deg)` }}
                  />
                </div>
                <p className="text-white text-lg sm:text-[32px] font-thin leading-tight">
                  We are Design Agency Specialized in Illustrations, UI/UX Design <br />
                  and Motion Graphic Based in Yogyakarta, Indonesia
                </p>
              </div>
            </div>
          </div>
        </section>
      </Container>

      <WhyUs />
      <OurService />
      <WorkingProcess />
      <OurLatestWork />
      <FAQ />
      <ContactUs />

      {/* Footer */}
      <Footer />
    </>
  )
}
